title: TaskFree
description: Privacy-first, open-source task manager
theme: minima
logo: /assets/logo_small.png
show_downloads: true

# Optional: navigation links (appear in header/footer depending on theme)
header_pages:
  - index.md

# Social/metadata
github:
  is_project_page: true
  repository_url: https://github.com/app-muon/AndroidTaskFree
