title: TaskFree
description: Simple open-source task manager with reminders and categories
theme: minima
show_downloads: true

# recommended for project pages
url: https://app-muon.github.io
baseurl: /AndroidTaskFree
