title: TaskFree
description: Privacy-first, open-source task manager
theme: minima
logo: /assets/logo_small.png
show_downloads: true

# Optional nav (index is fine to list, or remove this section entirely)
header_pages:
  - index.md

# Recommended for project pages
url: https://app-muon.github.io
baseurl: /AndroidTaskFree
